# example/pubspec.yaml

name: smart_lib_form_elements_example
description: Example app for smart_lib_form_elements package.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  smart_lib_form_elements:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter