name: smart_lib_form_elements_example
description: Example project for smart_lib_form_elements
publish_to: 'none'

dependencies:
  flutter:
    sdk: flutter
  smart_lib_form_elements:
    path: ../

flutter:
  uses-material-design: true