name: smart_lib_form_elements
description: "Flutter library with pre-styled form elements (CheckBox, Calendar, Photo Picker, Radio, Text Inputs) for rapid UI development"
version: 1.0.0+1

homepage: https://github.com/Vanik98/smart_lib_form_elements
repository: https://github.com/Vanik98/smart_lib_form_elements
issue_tracker: https://github.com/Vanik98/smart_lib_form_elements/issues
documentation: https://github.com/Vanik98/smart_lib_form_elements/wiki

environment:
  sdk: ^3.7.2
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

authors:
  - Vanik Dallakyan <vanik.dallakyan@yourdomain.com>
  - GitHub: https://github.com/Vanik98
  - LinkedIn: https://www.linkedin.com/in/vanik-dallakyan-756b4a1a2/

keywords:
  - flutter
  - form
  - widgets
  - validation
  - calendar
  - checkbox
  - photo
  - radio
  - textfield
  - material